
title: Sergio Edgardo Urzúa Correa
name: Sergio Edgardo Urzúa Correa
description: "Robotics Engineer & PhD Researcher"
url: "https://sergio1817.github.io"
baseurl: "" 

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"

# Author Data
author:
  name: "Sergio Edgardo Urzúa Correa"
  bio: "Bridging Control Theory & Embedded Engineering."
  location: "Compiègne, France / Mexico"
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/sergio-uc"
      icon: "fab fa-fw fa-linkedin"
    - label: "GitHub"
      url: "https://github.com/sergio1817"
      icon: "fab fa-fw fa-github"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=qwpVD6cAAAAJ"
      icon: "fas fa-fw fa-graduation-cap"

# Build Settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/header-drone.jpg
