
name: Update Publications from ORCID

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  get-publications:
    runs-on: ubuntu-latest
    permissions:
      contents: write # REQUIRED to save the new file
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Fetch ORCID Data
        id: getOrcidPublications
        uses: TheAlbertDev/get-orcid-publications@v0.1.0
        with:
          orcidId: "0009-0009-4185-9405" # Sergio's ORCID
          publicationsFilePath: "_data/"
          publicationsFileName: "orcid_pubs"
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add _data/orcid_pubs.yml
          git diff --quiet && git diff --staged --quiet |

| git commit -m "Auto-update publications from ORCID"
          git push
